version: "3.8"

services:

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: iot_data
      MYSQL_USER: iotuser
      MYSQL_PASSWORD: iotpass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8080:80"

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    user: "root"
    environment:
      - NODE_RED_ENABLE_PROJECTS=false
      - NODE_RED_HTTP_NODE_ROOT=/nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: iot_history
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mytoken
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      - /home/linh/iot-web/www/ngothithuylinh.com:/var/www/ngothithuylinh.com
      - /home/linh/iot-web/nginx_conf:/etc/nginx/conf.d

volumes:
  mariadb_data:
  nodered_data:
  influxdb_data:
  grafana_data:

