server {
    listen 8088;
    server_name ngothithuylinh.com;

    root /var/www/ngothithuylinh.com;
    index index.html;

    # Node-RED
    location /nodered/ {
        rewrite ^/nodered(/.*)? $1 break;
        proxy_pass http://nodered:1880;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Grafana
    location /grafana/ {
        rewrite ^/grafana(/.*)? $1 break;
        proxy_pass http://grafana:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # phpMyAdmin
    location /phpmyadmin/ {
        rewrite ^/phpmyadmin(/.*)? $1 break;
        proxy_pass http://phpmyadmin:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # SPA Web IoT
    location / {
        try_files $uri /index.html;
    }

} 
